const https = require('https');
const fs = require('fs');

const url = 'https://www.giggiplay.online/feeds/posts/default';

https.get(url, (res) => {
    let data = '';

    // Response data collect karna
    res.on('data', (chunk) => {
        data += chunk;
    });

    // Jab pura data aa jaye
    res.on('end', () => {
        // Data ko file me save karna (output.xml)
        fs.writeFileSync('output.xml', data, 'utf8');
        console.log('RSS feed downloaded successfully!');
    });

}).on('error', (err) => {
    // Error handle karna
    console.error('Error fetching RSS feed:', err.message);
    // Error ko file me bhi likhna
    fs.writeFileSync('fetchBlogger.error.log', err.stack || err.message, 'utf8');
    process.exit(1);
});
